import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

const Home: React.VFC = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>test studio</h1>

        <p className={styles.description}>クオリティの高い野球用品をご提供します。</p>

        <div className={styles.grid}>
          <Link href="/product">
            <a className={styles.card}>
              <h2>製品ラインナップへ</h2>
              <p></p>
            </a>
          </Link>

          <Link href="/agancy">
            <a className={styles.card}>
              <h2>お取扱店一覧</h2>
              <p></p>
            </a>
          </Link>

          <Link href="/about">
            <a className={styles.card}>
              <h2>会社概要</h2>
              <p></p>
            </a>
          </Link>

          <Link href="/contact">
            <a className={styles.card}>
              <h2>お問い合わせ</h2>
              <p></p>
            </a>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Copryright © Test Studio Inc. All Rights Reserved.
        </a>
      </footer>
    </div>
  )
}

export default Home
