import React from 'react'
import Head from 'next/head'
import Header from './organisms/header'
import { Box, Flex, Text } from '@chakra-ui/react'

const Layout: React.FC = ({ children }) => {
  return (
    <Box>
      <Head>
        <title>i studio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Box
        backgroundImage="url('/backgroundImg.png')"
        backgroundPosition="center"
        backgroundRepeat="no-repeat"
        backgroundSize="cover"
      >
        {children}
      </Box>
      <Flex
        as={'footer'}
        justifyContent={'center'}
        alignItems={'center'}
        width={'full'}
        height={'100px'}
        backgroundColor={'gray.100'}
      >
        <Text textAlign={'center'}>Copryright © i studio Inc. All Rights Reserved.</Text>
      </Flex>
    </Box>
  )
}

export default Layout
