import React from 'react'
import styles from '../styles/Home.module.css'
import Head from 'next/head'
import Header from './organisms/header'
import { Box } from '@chakra-ui/react'

const Layout: React.FC = ({ children }) => {
  return (
    <Box>
      <Head>
        <title>i studio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Box
        backgroundImage="url('/backgroundImg.png')"
        backgroundPosition="center"
        backgroundRepeat="no-repeat"
        backgroundSize="cover"
      >
        {' '}
        {children}
      </Box>
      <footer className={styles.footer}>
        <p>Copryright © i studio Inc. All Rights Reserved.</p>{' '}
      </footer>
    </Box>
  )
}

export default Layout
