import React from 'react'
import styles from '../styles/Home.module.css'
import Head from 'next/head'
import Header from './header'

const Layout: React.FC = ({ children }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {children}
      <footer className={styles.footer}>
        <p>Copryright © i studio Inc. All Rights Reserved.</p>{' '}
      </footer>
    </div>
  )
}

export default Layout
